Repository phpmetrics/PhpMetrics, pull requests merged in 2020-06, with the labels that each got.

#428 Way to analyze by layer
  README.md
  config-example.json
  config.json
  doc/installation.md
  src/Hal/Application/Config/File/ConfigFileReaderJson.php
  src/Hal/Application/Config/Validator.php
  src/Hal/Metric/Group/Group.php
  src/Hal/Report/Html/Reporter.php
  src/functions.php
  templates/html_report/_footer.php
  templates/html_report/_header.php
  templates/html_report/css/style.css
  templates/html_report/index.php
  templates/html_report/loc.php
  tests/Application/Config/File/ConfigFileReaderTest.php
  tests/Application/Config/File/examples/config.json
  tests/binary/examples/1/file1.php
Labels: enhancement

#430 Fix #429, bug when generating html report.
  src/Hal/Report/Html/Reporter.php
Labels: bug

#432 Fix #431, only outdated packages will be reported
  src/Hal/Metric/System/Packages/Composer/Composer.php
Labels: bug

#434 Bump php package required
  artifacts/debian/control
Labels: Compatibility

#437 Fix issue with charts in groups - Closes #429, Closes #433
  src/Hal/Metric/Consolidated.php
  src/Hal/Report/Html/Reporter.php
  tests/Report/Html/ReporterTest.php
Labels: bug
